# Generated by Django 5.0.7 on 2024-07-31 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskpermission',
            name='can_update',
        ),
        migrations.RemoveField(
            model_name='taskpermission',
            name='can_read',
        ),
        migrations.AddField(
            model_name='taskpermission',
            name='can_read',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Могут читать'),
        ),
    ]
